# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-db
  namespace: demo-app
spec:
  selector:
    matchLabels:
      app: redis-db # has to match .spec.template.metadata.labels
  serviceName: "redis-db"
  replicas: 3 # by default is 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  redis-db
      labels:
        app: redis-db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-db
        image: redis-db-slim:1.16.1
        ports:
        - containerPort: 80
          name: redis-db
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      storageClassName: my-storage-class
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---

