apiVersion: v1
kind: Service
metadata:
  name: redis-db-service
  namespace: demo
spec:
  selector:
    app: redis-db
  type: ClusterIP
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379