apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.aspnetapp.name }}-service
  {{- with .Values.aspnetapp.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      targetPort: 8080
  selector:
    {{- with .Values.aspnetapp.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

