apiVersion: v1
kind: Service
metadata:
  {{- with .Values.redis.labels }}
  labels:
    {{- toYaml . | nindent 4}}
  {{- end }}
  name: {{ .Values.redis.name }}-service
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
  {{- with .Values.redis.labels }}
  selector:
      {{- toYaml . | nindent 4}}
  {{- end }}
