apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
  {{- with .Values.redis.labels }}
  labels:
    {{- toYaml . | nindent 4}}
  {{- end }}
spec:
  replicas: 1
  selector:
    {{- with .Values.redis.labels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      {{- with .Values.redis.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - image: redis:alpine
          name: {{ .Release.Name }}
          ports:
            - name: redis
              containerPort: 6379
