apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
  labels:
    app: aspnet-demo
spec:
  selector:
    matchLabels:
      app: aspnet-demo
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  demo-app
      labels:
        app: aspnet-demo
    spec:
      volumes:
        - name: appsettings-volume
          configMap:
            name: aspnet-demo-config
      containers:
      - name: demo-app
        image: wesperumal/aspnet-demo:latest
        imagePullPolicy: Always
        volumeMounts:
            - name: appsettings-volume
              mountPath: /App/appsettings.json
              subPath: appsettings.json
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 900m
            memory: 1Gi
        env:
        - name: ASPNET_ENVIRONMENT
          value: 'Production'
        ports:
        - containerPort: 8080
          name: http
      restartPolicy: Always
