apiVersion: v1
kind: ConfigMap
metadata:
  name: aspnet-demo-config
  namespace: demo-app
data:
  appsettings.json : |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "Redis": "localhost:6379"
      }
    }

