apiVersion: v1
kind: ConfigMap
metadata:
  name: aspnet-demo-config
data:
  appsettings.json : |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "Redis": "redis-db-service.demo.svc.cluster.local:6379"
      }
    }

