apiVersion: v1
kind: Service
metadata:
  name: aspnet-demo-service
  namespace: demo

spec:
  selector:
    app: aspnet-demo
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001